// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nitro/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRecordTransactionData struct {
	Sender    string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender"`
	Slot      uint64   `protobuf:"varint,2,opt,name=slot,proto3" json:"slot"`
	StateRoot string   `protobuf:"bytes,3,opt,name=stateRoot,proto3" json:"state_root"`
	Txs       []string `protobuf:"bytes,4,rep,name=txs,proto3" json:"txs"`
}

func (m *MsgRecordTransactionData) Reset()         { *m = MsgRecordTransactionData{} }
func (m *MsgRecordTransactionData) String() string { return proto.CompactTextString(m) }
func (*MsgRecordTransactionData) ProtoMessage()    {}
func (*MsgRecordTransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa387fcec7e73aca, []int{0}
}
func (m *MsgRecordTransactionData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordTransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordTransactionData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordTransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordTransactionData.Merge(m, src)
}
func (m *MsgRecordTransactionData) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordTransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordTransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordTransactionData proto.InternalMessageInfo

func (m *MsgRecordTransactionData) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRecordTransactionData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *MsgRecordTransactionData) GetStateRoot() string {
	if m != nil {
		return m.StateRoot
	}
	return ""
}

func (m *MsgRecordTransactionData) GetTxs() []string {
	if m != nil {
		return m.Txs
	}
	return nil
}

type MsgSubmitFraudChallenge struct {
	Sender        string       `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender"`
	StartSlot     uint64       `protobuf:"varint,2,opt,name=startSlot,proto3" json:"start_slot"`
	EndSlot       uint64       `protobuf:"varint,3,opt,name=endSlot,proto3" json:"end_slot"`
	FraudState    string       `protobuf:"bytes,4,opt,name=fraudState,proto3" json:"fraud_state"`
	MerkleProof   *MerkleProof `protobuf:"bytes,5,opt,name=merkleProof,proto3" json:"merkle_proof"`
	AccountStates []*Account   `protobuf:"bytes,6,rep,name=accountStates,proto3" json:"account_states"`
	Programs      []*Account   `protobuf:"bytes,7,rep,name=programs,proto3" json:"programs"`
}

func (m *MsgSubmitFraudChallenge) Reset()         { *m = MsgSubmitFraudChallenge{} }
func (m *MsgSubmitFraudChallenge) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitFraudChallenge) ProtoMessage()    {}
func (*MsgSubmitFraudChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa387fcec7e73aca, []int{1}
}
func (m *MsgSubmitFraudChallenge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitFraudChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitFraudChallenge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitFraudChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitFraudChallenge.Merge(m, src)
}
func (m *MsgSubmitFraudChallenge) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitFraudChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitFraudChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitFraudChallenge proto.InternalMessageInfo

func (m *MsgSubmitFraudChallenge) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgSubmitFraudChallenge) GetStartSlot() uint64 {
	if m != nil {
		return m.StartSlot
	}
	return 0
}

func (m *MsgSubmitFraudChallenge) GetEndSlot() uint64 {
	if m != nil {
		return m.EndSlot
	}
	return 0
}

func (m *MsgSubmitFraudChallenge) GetFraudState() string {
	if m != nil {
		return m.FraudState
	}
	return ""
}

func (m *MsgSubmitFraudChallenge) GetMerkleProof() *MerkleProof {
	if m != nil {
		return m.MerkleProof
	}
	return nil
}

func (m *MsgSubmitFraudChallenge) GetAccountStates() []*Account {
	if m != nil {
		return m.AccountStates
	}
	return nil
}

func (m *MsgSubmitFraudChallenge) GetPrograms() []*Account {
	if m != nil {
		return m.Programs
	}
	return nil
}

type MsgRecordTransactionDataResponse struct {
}

func (m *MsgRecordTransactionDataResponse) Reset()         { *m = MsgRecordTransactionDataResponse{} }
func (m *MsgRecordTransactionDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRecordTransactionDataResponse) ProtoMessage()    {}
func (*MsgRecordTransactionDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa387fcec7e73aca, []int{2}
}
func (m *MsgRecordTransactionDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordTransactionDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordTransactionDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordTransactionDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordTransactionDataResponse.Merge(m, src)
}
func (m *MsgRecordTransactionDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordTransactionDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordTransactionDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordTransactionDataResponse proto.InternalMessageInfo

type MsgSubmitFraudChallengeResponse struct {
}

func (m *MsgSubmitFraudChallengeResponse) Reset()         { *m = MsgSubmitFraudChallengeResponse{} }
func (m *MsgSubmitFraudChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitFraudChallengeResponse) ProtoMessage()    {}
func (*MsgSubmitFraudChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa387fcec7e73aca, []int{3}
}
func (m *MsgSubmitFraudChallengeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitFraudChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitFraudChallengeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitFraudChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitFraudChallengeResponse.Merge(m, src)
}
func (m *MsgSubmitFraudChallengeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitFraudChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitFraudChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitFraudChallengeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRecordTransactionData)(nil), "seiprotocol.seichain.nitro.MsgRecordTransactionData")
	proto.RegisterType((*MsgSubmitFraudChallenge)(nil), "seiprotocol.seichain.nitro.MsgSubmitFraudChallenge")
	proto.RegisterType((*MsgRecordTransactionDataResponse)(nil), "seiprotocol.seichain.nitro.MsgRecordTransactionDataResponse")
	proto.RegisterType((*MsgSubmitFraudChallengeResponse)(nil), "seiprotocol.seichain.nitro.MsgSubmitFraudChallengeResponse")
}

func init() { proto.RegisterFile("nitro/tx.proto", fileDescriptor_fa387fcec7e73aca) }

var fileDescriptor_fa387fcec7e73aca = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x8b, 0xd3, 0x40,
	0x1c, 0x6d, 0x36, 0xb5, 0x7f, 0x7e, 0x5d, 0xeb, 0x32, 0xae, 0x18, 0x8b, 0x24, 0x31, 0x82, 0xf6,
	0xa0, 0x09, 0x74, 0xbd, 0xe9, 0xc5, 0x28, 0x82, 0x87, 0x82, 0xa4, 0x9e, 0x14, 0x29, 0xd3, 0x64,
	0x36, 0x0d, 0xb6, 0x99, 0x32, 0x33, 0x85, 0xfa, 0x0d, 0x04, 0x2f, 0x7e, 0x02, 0x6f, 0x7e, 0x17,
	0x6f, 0xee, 0xd1, 0x53, 0x90, 0xf6, 0x96, 0x4f, 0x21, 0x99, 0x49, 0xec, 0x0a, 0xed, 0xba, 0xec,
	0x65, 0x32, 0xf3, 0xe6, 0xbd, 0xf7, 0x7b, 0x33, 0xf3, 0x23, 0xd0, 0x4d, 0x13, 0xc1, 0xa8, 0x27,
	0x56, 0xee, 0x82, 0x51, 0x41, 0x51, 0x8f, 0x93, 0x44, 0xce, 0x42, 0x3a, 0x73, 0x39, 0x49, 0xc2,
	0x29, 0x4e, 0x52, 0x57, 0x92, 0x7a, 0xc7, 0x31, 0x8d, 0xa9, 0xdc, 0xf4, 0x8a, 0x99, 0x52, 0xf4,
	0x8e, 0x94, 0x43, 0x84, 0x05, 0x2e, 0x91, 0x9b, 0x0a, 0xc1, 0x61, 0x48, 0x97, 0xa9, 0x50, 0xa0,
	0xf3, 0x5d, 0x03, 0x63, 0xc8, 0xe3, 0x80, 0x84, 0x94, 0x45, 0x6f, 0x19, 0x4e, 0x39, 0x0e, 0x45,
	0x42, 0xd3, 0x97, 0x58, 0x60, 0xe4, 0x40, 0x83, 0x93, 0x34, 0x22, 0xcc, 0xd0, 0x6c, 0xad, 0xdf,
	0xf6, 0x21, 0xcf, 0xac, 0x12, 0x09, 0xca, 0x2f, 0xba, 0x0b, 0x75, 0x3e, 0xa3, 0xc2, 0x38, 0xb0,
	0xb5, 0x7e, 0xdd, 0x6f, 0xe5, 0x99, 0x25, 0xd7, 0x81, 0x1c, 0xd1, 0x23, 0x68, 0x73, 0x81, 0x05,
	0x09, 0x28, 0x15, 0x86, 0x2e, 0x4d, 0xba, 0x79, 0x66, 0x81, 0x04, 0xc7, 0x8c, 0x52, 0x11, 0x6c,
	0x09, 0xe8, 0x0e, 0xe8, 0x62, 0xc5, 0x8d, 0xba, 0xad, 0xf7, 0xdb, 0x7e, 0x33, 0xcf, 0xac, 0x62,
	0x19, 0x14, 0x83, 0xf3, 0x53, 0x87, 0xdb, 0x43, 0x1e, 0x8f, 0x96, 0x93, 0x79, 0x22, 0x5e, 0x31,
	0xbc, 0x8c, 0x5e, 0x4c, 0xf1, 0x6c, 0x46, 0xd2, 0x98, 0x5c, 0x2a, 0xa6, 0x0a, 0xc2, 0xc4, 0x68,
	0x9b, 0xb5, 0x0a, 0xc2, 0xc4, 0x58, 0x26, 0xde, 0x12, 0xd0, 0x03, 0x68, 0x92, 0x34, 0x92, 0x5c,
	0x5d, 0x72, 0x0f, 0xf3, 0xcc, 0x6a, 0x91, 0x34, 0x52, 0xcc, 0x6a, 0x13, 0x79, 0x00, 0xa7, 0x45,
	0x96, 0x51, 0x71, 0x04, 0xa3, 0x2e, 0xab, 0xdf, 0xc8, 0x33, 0xab, 0x23, 0xd1, 0xb1, 0x3a, 0xd9,
	0x39, 0x0a, 0x7a, 0x0f, 0x9d, 0x39, 0x61, 0x1f, 0x67, 0xe4, 0x0d, 0xa3, 0xf4, 0xd4, 0xb8, 0x66,
	0x6b, 0xfd, 0xce, 0xe0, 0xa1, 0xbb, 0xff, 0x75, 0xdd, 0xe1, 0x96, 0xee, 0x1f, 0xe5, 0x99, 0x75,
	0xa8, 0xf4, 0xe3, 0x45, 0x81, 0x04, 0xe7, 0xdd, 0xd0, 0x07, 0xb8, 0x5e, 0x3e, 0xae, 0x2c, 0xc6,
	0x8d, 0x86, 0xad, 0xf7, 0x3b, 0x83, 0xfb, 0x17, 0xd9, 0x3f, 0x57, 0x02, 0x1f, 0xe5, 0x99, 0xd5,
	0x2d, 0xd5, 0x2a, 0x37, 0x0f, 0xfe, 0x75, 0x43, 0x43, 0x68, 0x2d, 0x18, 0x8d, 0x19, 0x9e, 0x73,
	0xa3, 0x79, 0x79, 0x67, 0x79, 0x75, 0x95, 0x30, 0xf8, 0x3b, 0x73, 0x1c, 0xb0, 0xf7, 0x35, 0x5e,
	0x40, 0xf8, 0x82, 0xa6, 0x9c, 0x38, 0xf7, 0xc0, 0xda, 0xf3, 0xe8, 0x15, 0x65, 0xf0, 0xed, 0x00,
	0xf4, 0x21, 0x8f, 0xd1, 0x17, 0x0d, 0x6e, 0xed, 0xee, 0xe2, 0x27, 0x17, 0x5e, 0xef, 0x9e, 0x08,
	0xbd, 0x67, 0x57, 0x51, 0x55, 0xa9, 0xd0, 0x67, 0x0d, 0x8e, 0x77, 0xf6, 0xea, 0xc9, 0x7f, 0x6c,
	0x77, 0x89, 0x7a, 0x4f, 0xaf, 0x20, 0xaa, 0xa2, 0xf8, 0xaf, 0x7f, 0xac, 0x4d, 0xed, 0x6c, 0x6d,
	0x6a, 0xbf, 0xd7, 0xa6, 0xf6, 0x75, 0x63, 0xd6, 0xce, 0x36, 0x66, 0xed, 0xd7, 0xc6, 0xac, 0xbd,
	0xf3, 0xe2, 0x44, 0x4c, 0x97, 0x13, 0x37, 0xa4, 0x73, 0x8f, 0x93, 0xe4, 0x71, 0x55, 0x41, 0x2e,
	0x64, 0x09, 0x6f, 0xe5, 0x95, 0x3f, 0xa2, 0x4f, 0x0b, 0xc2, 0x27, 0x0d, 0xc9, 0x38, 0xf9, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xf5, 0x81, 0x8b, 0x9b, 0x9e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RecordTransactionData(ctx context.Context, in *MsgRecordTransactionData, opts ...grpc.CallOption) (*MsgRecordTransactionDataResponse, error)
	SubmitFraudChallenge(ctx context.Context, in *MsgSubmitFraudChallenge, opts ...grpc.CallOption) (*MsgSubmitFraudChallengeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RecordTransactionData(ctx context.Context, in *MsgRecordTransactionData, opts ...grpc.CallOption) (*MsgRecordTransactionDataResponse, error) {
	out := new(MsgRecordTransactionDataResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.nitro.Msg/RecordTransactionData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitFraudChallenge(ctx context.Context, in *MsgSubmitFraudChallenge, opts ...grpc.CallOption) (*MsgSubmitFraudChallengeResponse, error) {
	out := new(MsgSubmitFraudChallengeResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.nitro.Msg/SubmitFraudChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RecordTransactionData(context.Context, *MsgRecordTransactionData) (*MsgRecordTransactionDataResponse, error)
	SubmitFraudChallenge(context.Context, *MsgSubmitFraudChallenge) (*MsgSubmitFraudChallengeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RecordTransactionData(ctx context.Context, req *MsgRecordTransactionData) (*MsgRecordTransactionDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordTransactionData not implemented")
}
func (*UnimplementedMsgServer) SubmitFraudChallenge(ctx context.Context, req *MsgSubmitFraudChallenge) (*MsgSubmitFraudChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitFraudChallenge not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RecordTransactionData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRecordTransactionData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RecordTransactionData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.nitro.Msg/RecordTransactionData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RecordTransactionData(ctx, req.(*MsgRecordTransactionData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitFraudChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitFraudChallenge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitFraudChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.nitro.Msg/SubmitFraudChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitFraudChallenge(ctx, req.(*MsgSubmitFraudChallenge))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seiprotocol.seichain.nitro.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordTransactionData",
			Handler:    _Msg_RecordTransactionData_Handler,
		},
		{
			MethodName: "SubmitFraudChallenge",
			Handler:    _Msg_SubmitFraudChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nitro/tx.proto",
}

func (m *MsgRecordTransactionData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordTransactionData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordTransactionData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Txs) > 0 {
		for iNdEx := len(m.Txs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Txs[iNdEx])
			copy(dAtA[i:], m.Txs[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Txs[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Slot != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Slot))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitFraudChallenge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitFraudChallenge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitFraudChallenge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Programs) > 0 {
		for iNdEx := len(m.Programs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Programs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.AccountStates) > 0 {
		for iNdEx := len(m.AccountStates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccountStates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.MerkleProof != nil {
		{
			size, err := m.MerkleProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.FraudState) > 0 {
		i -= len(m.FraudState)
		copy(dAtA[i:], m.FraudState)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FraudState)))
		i--
		dAtA[i] = 0x22
	}
	if m.EndSlot != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndSlot))
		i--
		dAtA[i] = 0x18
	}
	if m.StartSlot != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartSlot))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordTransactionDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordTransactionDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordTransactionDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitFraudChallengeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitFraudChallengeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitFraudChallengeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRecordTransactionData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Slot != 0 {
		n += 1 + sovTx(uint64(m.Slot))
	}
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Txs) > 0 {
		for _, s := range m.Txs {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSubmitFraudChallenge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StartSlot != 0 {
		n += 1 + sovTx(uint64(m.StartSlot))
	}
	if m.EndSlot != 0 {
		n += 1 + sovTx(uint64(m.EndSlot))
	}
	l = len(m.FraudState)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MerkleProof != nil {
		l = m.MerkleProof.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.AccountStates) > 0 {
		for _, e := range m.AccountStates {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.Programs) > 0 {
		for _, e := range m.Programs {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRecordTransactionDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitFraudChallengeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRecordTransactionData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordTransactionData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordTransactionData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txs = append(m.Txs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitFraudChallenge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitFraudChallenge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitFraudChallenge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartSlot", wireType)
			}
			m.StartSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndSlot", wireType)
			}
			m.EndSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FraudState", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FraudState = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MerkleProof == nil {
				m.MerkleProof = &MerkleProof{}
			}
			if err := m.MerkleProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountStates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountStates = append(m.AccountStates, &Account{})
			if err := m.AccountStates[len(m.AccountStates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Programs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Programs = append(m.Programs, &Account{})
			if err := m.Programs[len(m.Programs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordTransactionDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordTransactionDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordTransactionDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitFraudChallengeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitFraudChallengeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitFraudChallengeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
